czat2/czat/urls.py
# -*- coding: utf-8 -*-
# czat/urls.py

from django.conf.urls import url
from . import views  # import widoków aplikacji
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from czat.models import Wiadomosc
from django.views.generic import DeleteView

app_name = 'czat'  # przestrzeń nazw aplikacji
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rejestracja/', CreateView.as_view(template_name='czat/rejestracja.html', form_class=UserCreationForm , success_url=reverse_lazy('czat:index'))),
    url(r'^logowanie/', auth_views.login, {'template_name': 'czat/logowanie.html'}, name='logowanie'),
    url(r'^wylogowanie/', auth_views.logout, {'next_page' : reverse_lazy('czat:index')}, name='wylogowanie' ),
    url(r'^wiadomosci/', login_required(ListView.as_view(model=Wiadomosc, context_object_name='wiadomosci', paginate_by=5)), name='wiadomosci'),
    url(r'^dodaj/$', login_required(views.DodajWiadomosc.as_view(),login_url='/logowanie'), name='dodaj'),
    url(r'^edytuj/(?P<pk>\d+)/', login_required( views.EdytujWiadomosc.as_view(), login_url='/logowanie'), name='edytuj'),
    url(r'^usun/(?P<pk>\d+)/', login_required( DeleteView.as_view(model=Wiadomosc, template_name='czat/wiadomosc_usun.html', success_url = '/wiadomosci'), login_url='/logowanie'), name='usun'),

]

czat2/czat2/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^', include('czat.urls')),
    url(r'^admin/', admin.site.urls),
]

czat2/czat/models.py
# -*- coding: utf-8 -*-
# czat/models.py

from django.db import models
from django.contrib.auth.models import User


class Wiadomosc(models.Model):

    """Klasa reprezentująca wiadomość w systemie"""
    tekst = models.CharField('treść wiadomości', max_length=300)
    data_pub = models.DateTimeField('data publikacji', auto_now_add=False)
    autor = models.ForeignKey(User)

    class Meta:  
        verbose_name = u'wiadomość'  
        verbose_name_plural = u'wiadomości'  
        ordering = ['data_pub']  

    def __str__(self):
        return self.tekst  

czat2/czat/forms.py
from django.forms import ModelForm, TextInput
from czat.models import Wiadomosc
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class EdytujWiadomoscForm(ModelForm):
	class Meta:
		model = Wiadomosc
		fields = ['tekst', 'data_pub']
		exclude = ['autor']
		widgets = {'tekst': TextInput(attrs={'size' : 60})}

czat2/czat/views.py
# -*- coding: utf-8 -*-
# czat/views.py

from django.shortcuts import render
from django.views.generic.edit import CreateView
from czat.models import Wiadomosc
from django.utils import timezone
from django.contrib import messages
from django.views.generic.edit import UpdateView


# from django.http import HttpResponse


def index(request):
    """Strona główna aplikacji."""
    return render(request, 'czat/index.html')


class DodajWiadomosc(CreateView):
	model = Wiadomosc
	fields = ['tekst', 'data_pub' ]
	context_object_name = 'wiadomosci'
	success_url = '/dodaj'
	
	def get_initial(self):
		initial = super(DodajWiadomosc, self).get_initial()
		initial['data_pub'] = timezone.now()
		return initial
	def get_context_data(self, **kwargs):
		context = super(DodajWiadomosc, self).get_context_data(**kwargs)
		context['wiadomosci'] = Wiadomosc.objects.all()
		return context 
	def form_valid(self, form):
		wiadomosc = form.save(commit=False)
		wiadomosc.autor = self.request.user
		wiadomosc.save()
		messages.success(self.request, "Dodano wiadomosść")
		return super (DodajWiadomosc, self).form_valid(form)
class EdytujWiadomosc(UpdateView):
	model = Wiadomosc
	from czat.forms import EdytujWiadomoscForm
	form_class = EdytujWiadomoscForm
	context_object_name = 'wiadomosci'
	template_name = 'czat/wiadomosc_form.html'
	success_url = '/wiadomosci'

	def get_context_data(self, **kwargs):
		context = super(EdytujWiadomosc, self).get_context_data(**kwargs)
		context['wiadomosci'] = Wiadomosc.objects.filter(autor=self.request.user)
		return context 
	def get_object(self, queryset=None):
		wiadomosc = Wiadomosc.objects.get(id=self.kwargs['pk'])
		return wiadomosc

czat2/czat/templates/czat/index.html
<!-- templates/czat/index.html -->
{% load staticfiles %}
<html>
  <head>
    <style>

	#first {
   		 position: relative; left: 30%
  	}
	
	p.tekst {
		 font-family: Georgia, Arial ;
		 font-size: 25px ;
		 color: teal;
		 text-shadow: 1px 1px 5px silver;
   	
  	}
	
	p.standard {
		 font-family: Georgia, Arial ;
		 font-size: 20px ;
		 color: teal;
		 text-shadow: 1px 1px 5px gray;
   		 position: relative; left: 30%
  	}
	p.baner {
		 font-size: x-large;
		 color: teal;
		 text-shadow: 1px 1px 5px teal;
   		 position: relative; left: 30%
  	}
	p.tytul {
		 font-family: Verdana, Arial, Georgia ; 
		 font-size: 50px ;
		 color: teal;
		 position: relative; left: 10%;
		 text-shadow: 1px 1px 3px silver;
	}
 	.container {
     	width: 100%;
    	 background-color: teal;
  	}
 	.content {
 	    width: 40%;
    	 background-color: white;
        }
    </style>
  </head>
  <body bgcolor="white" >
	<div class="container">
   		<div class="content">
    			<p class="baner"> Team <=> Chat</p>
   		</div>
	</div>
    <p class="tytul">Witaj w aplikacji Team <=> Chat</p>
    
		{% if user.is_authenticated %}
			<p class ="tekst">Jesteś zalogowany jako <i>{{ user.username }}.</i></p>
			
			<p ><a href="wiadomosci"><img src="{% static 'czat/img/listwiad.png' %}" width="300" title="Historia czatu"/></a>
			<a href="dodaj"><img src="{% static 'czat/img/addwiad.png' %}" width="300" title="Dodaj nową wiadomość"/></a>
			<a href="wylogowanie"><img src="{% static 'czat/img/wyl.jpeg' %}" title="Wyloguj się"/></a></p>
		{% else %}
			<p id="first"><a href="logowanie"><img src="{% static 'czat/img/login.png' %}" width="300" title="Logowanie"/></a></p>
			<p class="standard">A jeżeli nie masz konta kliknij tu :</p>
			<p id="first"><a href="rejestracja"><img src="{% static 'czat/img/rejestracja.png' %}" width="300" title="Zarejestruj się"/></a></p>

			
		{% endif %}
    <div id="obrazki">		
      <br />
      <p class="standard">Używamy technologii: </font></p>
      <img src="{% static 'czat/img/python.png' %}" width="300" />
      <img src="{% static 'czat/img/sqlite.png' %}" width="300" />
      <img src="{% static 'czat/img/image.png' %}" width="300" />	
    </div>
  </body>
</html>

czat2/czat/templates/czat/logowanie.html
{% load staticfiles %}
<html>

	<head>
    		<style>
			#first {
   				 position: relative; left: 30%
  			}
	
			p.standard {
				 font-family: Georgia, Arial ;
				 font-size: 20px ;
				 color: teal;
				 text-shadow: 1px 1px 5px gray;
   				 position: relative; left: 30%
  			}
			p.baner {
				 font-size: x-large;
		 		color: teal;
				 text-shadow: 1px 1px 5px teal;
   				 position: relative; left: 30%
  			}
			p.tytul {
				 font-family: Verdana, Arial, Georgia ; 
				 font-size: 50px ;
				 color: teal;
				 
				 text-shadow: 1px 1px 3px silver;
			}
 			.container {
     			width: 100%;
    			 background-color: teal;
  			}
 			.content {
 			    width: 40%;
    			 background-color: white;
      		        }
    </style>	
  </head>
	<body bgcolor="white" >
		<div class="container">
   			<div class="content">
    				<p class="baner"> Team <=> Chat</p>
   			</div>
		</div>

		<p class="tytul">Logowanie użytkownika</p>
		{% if user.is_authenticated %}
			<p>Jesteś już zalogowany jako {{user.username }}
			<br /><p id="first"><a href="/"><img src="{% static 'czat/img/strg.png' %}" width="300" title="Strona Główna"/></a></p>
		{% else %}
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Zaloguj się</button>

		</form>
		<br /><p id="first"><a href="/"><img src="{% static 'czat/img/strg.png' %}" width="300" title="Strona Główna"/></a></p>
		{% endif %}
	</body>
</html>

czat2/czat/templates/czat/rejestracja.html
{% load staticfiles %}
<html>
	<head>
    		<style>
			
	
			#first {
   		 		position: relative; left: 30%
  			}
	
			p.baner {
				 font-size: x-large;
		 		color: teal;
				 text-shadow: 1px 1px 5px teal;
   				 position: relative; left: 30%
  			}
			p.tytul {
				 font-family: Verdana, Arial, Georgia ; 
				 font-size: 50px ;
				 color: teal;
				 
				 text-shadow: 1px 1px 3px silver;
			}
 			.container {
     			width: 100%;
    			 background-color: teal;
  			}
 			.content {
 			    width: 40%;
    			 background-color: white;
      		        }
   		 </style>	
  	</head>
	<body bgcolor="white" >
		<div class="container">
   			<div class="content">
    				<p class="baner"> Team <=> Chat</p>
   			</div>
		</div>

		<p class="tytul">Rejestracja nowego użytkownika</p>
		{% if user.is_authenticated %}
			<p>Jesteś już zalogowany jako {{ user.username }}
			<br /><a href="/">Strona główna</a></p>
		{% else %}
			<form method="POST">
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit">Zarejestruj się</button>
			</form>
			<p id="first"><br /><a href="/"><img src="{% static 'czat/img/strg.png' %}" width="300" title="Strona Główna"/></a></p>
		{% endif %}
	</body>
</html>

czat2/czat/templates/czat/wiadomosc_form.html
{% load staticfiles %}
<html>
	<head>
    		<style>
			#first {
   		 		position: relative; left: 30%
  			}
			p.standard {
				 font-family: Georgia, Arial ;
				 font-size: 30px ;
				 color: teal;
				 text-shadow: 1px 1px 15px gray;
   				 
  			}
			
			p.baner {
				 font-size: x-large;
		 		color: teal;
				 text-shadow: 1px 1px 5px teal;
   				 position: relative; left: 30%
  			}
			p.tytul {
				 font-family: Verdana, Arial, Georgia ; 
				 font-size: 50px ;
				 color: teal;
				 
				 text-shadow: 1px 1px 3px silver;
			}
 			.container {
     			width: 100%;
    			 background-color: teal;
  			}
 			.content {
 			    width: 40%;
    			 background-color: white;
			}
      	
		</style>	        
	</head>
	<body bgcolor="white" >
		<div class="container">
   			<div class="content">
    				<p class="baner"> Team <=> Chat</p>
   			</div>
		</div>
		<p class="tytul">Wiadomości</p>
		<p class="standard">Dodaj wiadomość</h2>
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Zapisz</button>
		</form>
		<p class="standard">Historia czatu:</p>
		<ol>
			{% for wiadomosc in wiadomosci %}
			<li>
			<strong>{{ wiadomosc.autor.username }}</strong> ({{ wiadomosc.data_pub }}):
			<br /> {{ wiadomosc.tekst }}
			<br /> 				
			{% if wiadomosc.autor.username == user.username %}
					&bull; <a href="{% url 'czat:edytuj' wiadomosc.id %}">Edytuj</a>
			{% endif %}
			</li>
			{% endfor %}
		</ol>
		<p id="first"><a href="{% url 'czat:index' %}"><img src="{% static 'czat/img/strg.png' %}" width="300" title="Strona Główna"/></a></p>
	</body>
</html>

czat2/czat/templates/czat/wiadomosc_list.html
{% load staticfiles %}
<html>
	<head>
    		<style>
			#first {
   		 		position: relative; left: 30%
  			}
			p.standard {
				 font-family: Georgia, Arial ;
				 font-size: 30px ;
				 color: teal;
				 text-shadow: 1px 1px 15px gray;
   				 
  			}
			
			p.baner {
				 font-size: x-large;
		 		color: teal;
				 text-shadow: 1px 1px 5px teal;
   				 position: relative; left: 30%
  			}
			p.tytul {
				 font-family: Verdana, Arial, Georgia ; 
				 font-size: 50px ;
				 color: teal;
				 
				 text-shadow: 1px 1px 3px silver;
			}
 			.container {
     			width: 100%;
    			 background-color: teal;
  			}
 			.content {
 			    width: 40%;
    			 background-color: white;
      		        }
   		 </style>	
	<body bgcolor="white" >
		<div class="container">
   			<div class="content">
    				<p class="baner"> Team <=> Chat</p>
   			</div>
		</div>
		<p class="tytul">Wiadomości</p>
		{% if messages %}
			<ul>
				{% for komunikat in messages %}
					<li>{{ komunikat|capfirst }}</li>
				{% endfor %}
			</ul>
		{% endif %}
		<p class="standard">Historia czatu: </p>
		<ol>
			{% for wiadomosc in wiadomosci %}
			<li>
				<strong>{{ wiadomosc.autor.username }}</strong> ({{ wiadomosc.data_pub }}):
				<br /> {{ wiadomosc.tekst}}
				{% if wiadomosc.autor.username == user.username %}
					&bull; <a href="{% url 'czat:edytuj' wiadomosc.id %}">Edytuj</a>
					&bull; <a href="{% url 'czat:usun' wiadomosc.id %}">Usuń</a>
				{% endif %}
			</li>
			{% endfor %}
		</ol>
		{% if is_paginated %}
			<p>
			{% if page_obj.has_previous %}
				<a href="?page={{ page_obj.previous_page_number }}">Poprzednie</a>
			{% endif %}
			Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}.
			</span>
			{% if page_obj.has_next %}
				<a href="?page={{ page_obj.next_page_number }}">Następne</a>
			{% endif %}
			</p>
		{% endif %} 
		<p id="first"><a href="{% url 'czat:index' %}"><img src="{% static 'czat/img/strg.png' %}" width="300" title="Strona Główna"/></a></p>
	</body>
</html>

czat2/czat/templates/czat/wiadomosc_usun.html
{% load staticfiles %}
<html>
	<head>
    		<style>
			#first {
   		 		position: relative; left: 30%
  			}
			p.tekst {
				 font-family:  Arial ;
				 
				 color: red;
				 text-shadow: 1px 1px 10px gray;
   				 
  			}
			p.delete {
				 font-family: Georgia, Arial ;
				 font-size: 30px ;
				 color: red;
				 text-shadow: 1px 1px 15px red;
   				 
  			}
			p.baner {
				 font-size: x-large;
		 		color: teal;
				 text-shadow: 1px 1px 5px teal;
   				 position: relative; left: 30%
  			}
			p.tytul {
				 font-family: Verdana, Arial, Georgia ; 
				 font-size: 50px ;
				 color: teal;
				 
				 text-shadow: 1px 1px 3px silver;
			}
 			.container {
     			width: 100%;
    			 background-color: teal;
  			}
 			.content {
 			    width: 40%;
    			 background-color: white;
      		        }
   		 </style>	
  	</head>
	<body bgcolor="white" >
		<div class="container">
   			<div class="content">
    				<p class="baner"> Team <=> Chat</p>
   			</div>
		</div>
		<p class="tytul">Wiadomości</p>
		<p class="delete">Usuń wiadomość</p>
		<form method="POST">
			{% csrf_token %}
			<p class="tekst">Czy na pewno chcesz skasować poniższą wiadomość ? <br /><i><p>{{ object }}</p></i></p>
			<button type="submit">Usuń</button>
		</form>
		<p id="first"><a href="{% url 'czat:index' %}"><img src="{% static 'czat/img/strg.png' %}" width="300" title="Strona Główna"/></a></p>
	</body>
</html>